import { DashboardData } from "@/services/dashboardService";

const cadastros = [
  {
    id: "DEMO-001",
    idUnico: "DEMO-001",
    nome: "MARIA CLARA SOUZA",
    cpf: "12345678900",
    cnpj: "12345678000190",
    crm: "123456",
    ufCrm: "SP",
    especialidade: "Cardiologia",
    email: "maria.clara@exemplo.com",
    telefone: "11999999999",
    status: "PENDENTE" as const,
    dataCadastro: "2026-03-20",
    razaoSocial: "CLINICA MARIA CLARA LTDA",
    nomeFantasia: "Clínica Maria Clara",
    dataNascimento: "1985-04-10",
    enderecoCnpj: "Av. Paulista, 1000 - São Paulo/SP",
    vinculoCnpj: "Sócio",
    nomeTestemunha: "ANA LIMA",
    rgTestemunha: "1234567",
    emailTestemunha: "ana.lima@exemplo.com",
    observacoes: "Nome Fantasia: Clínica Maria Clara",
    pastaDriveId: "demo-drive-1",
    pastaDriveUrl: "https://drive.google.com/demo-1",
    tipoOperacao: "cadastro",
  },
  {
    id: "DEMO-002",
    idUnico: "DEMO-002",
    nome: "PAULO HENRIQUE COSTA",
    cpf: "98765432100",
    cnpj: "10987654000166",
    crm: "654321",
    ufCrm: "RJ",
    especialidade: "Ortopedia",
    email: "paulo.henrique@exemplo.com",
    telefone: "21988887777",
    status: "OK" as const,
    dataCadastro: "2026-03-18",
    razaoSocial: "PH COSTA SERVICOS MEDICOS LTDA",
    nomeFantasia: "Orto Costa",
    dataNascimento: "1979-11-22",
    enderecoCnpj: "Rua das Laranjeiras, 88 - Rio de Janeiro/RJ",
    vinculoCnpj: "Proprietário",
    nomeTestemunha: "CARLA MENDES",
    rgTestemunha: "7654321",
    emailTestemunha: "carla.mendes@exemplo.com",
    observacoes: "Nome Fantasia: Orto Costa",
    pastaDriveId: "demo-drive-2",
    pastaDriveUrl: "https://drive.google.com/demo-2",
    tipoOperacao: "cadastro",
  },
  {
    id: "DEMO-003",
    idUnico: "DEMO-003",
    nome: "FERNANDA ALVES DIAS",
    cpf: "45678912300",
    cnpj: "22446688000155",
    crm: "789123",
    ufCrm: "MG",
    especialidade: "Pediatria",
    email: "fernanda.alves@exemplo.com",
    telefone: "31977776666",
    status: "ERRO" as const,
    dataCadastro: "2026-03-15",
    razaoSocial: "FERNANDA DIAS MEDICINA LTDA",
    nomeFantasia: "Pediatria Dias",
    dataNascimento: "1988-08-03",
    enderecoCnpj: "Av. Afonso Pena, 450 - Belo Horizonte/MG",
    vinculoCnpj: "Contratado",
    nomeTestemunha: "ROBERTO SILVA",
    rgTestemunha: "9988776",
    emailTestemunha: "roberto.silva@exemplo.com",
    observacoes: "Nome Fantasia: Pediatria Dias",
    pastaDriveId: "demo-drive-3",
    pastaDriveUrl: "https://drive.google.com/demo-3",
    tipoOperacao: "cadastro",
    motivoInativacao: "Documentação divergente",
  },
];

export const mockDashboardData: DashboardData = {
  kpis: {
    total: cadastros.length,
    pendente: cadastros.filter((item) => item.status === "PENDENTE").length,
    ok: cadastros.filter((item) => item.status === "OK").length,
    inativo: cadastros.filter((item) => item.status === "INATIVO").length,
    erro: cadastros.filter((item) => item.status === "ERRO").length,
  },
  cadastros,
  top_especialidades: [
    { nome: "Cardiologia", total: 1 },
    { nome: "Ortopedia", total: 1 },
    { nome: "Pediatria", total: 1 },
  ],
  distribuicao_vinculo: [
    { nome: "Sócio", total: 1 },
    { nome: "Proprietário", total: 1 },
    { nome: "Contratado", total: 1 },
  ],
  ultimos_cadastros: cadastros.slice(0, 3),
};